"""SQLAlchemy DeclarativeBase shared by all ORM table models.

All five ORM models inherit from ``Base``.  Importing this module is enough
to access ``Base.metadata``, which Alembic uses for autogenerated migrations.

ARCH-INFRASTRUCTURE §3
"""
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Shared declarative base for all ORM table models.

    Carries no custom ``__init__`` or shared columns — each model is
    fully self-described.
    """
